---
# tasks file for vector-role
- name: Add vector user
  user:
    name: vector

- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: vector
    group: vector
    mode: 0755
  loop:
    - '/tmp/vector/'
    - "{{ vector_data_dir }}"
    - '/etc/vector'

- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/tmp/vector/vector-{{ vector_version }}.tar.gz"

- name: Unpack vector archive
  ansible.builtin.unarchive:
    src: "/tmp/vector/vector-{{ vector_version }}.tar.gz"
    dest: "/tmp/vector/"
    remote_src: yes

- name: Copy vector binary
  copy:
    src: "/tmp/vector/vector-x86_64-unknown-linux-musl/bin/vector"
    dest: "/usr/bin/vector"
    owner: vector
    group: vector
    mode: 0755
    remote_src: yes

- name: Copy vector service file
  copy:
    src: "/tmp/vector/vector-x86_64-unknown-linux-musl/etc/systemd/vector.service"
    dest: "/etc/systemd/system"
    #mode: 0644
    remote_src: yes

- name: Cleanup tmp
  file:
    path: "/tmp/vector"
    state: absent

- name: Copy conf template
  template:
    src: "vector.yaml.j2"
    dest: "/etc/vector/vector.yaml"
  notify: Restart vector service

- name: Flush handlers
  meta: flush_handlers